### ISSUE TITLE
very high GC lambda in imputed stats?

### ISSUE THREAD

**Issue by drveera** [sinarueeger/ssimp_software#14]
Hi I used your software to impute GWAS summary statistics. I started with around 400,000 variants and imputed to up to 90 million markers using EUR 1000 genomes as reference. There were around 5 million variants with r2pred > 0.8.  I see that the summary stats shows more H2 estimate (0.30 to 0.40) . But the GC lambda is very high 3.3. LD score regression estimates show intercept 1.7 and ratio 0.70. If I apply GC correction, the stats becomes flat, I lose all genomewide loci. Any ideas what could be the issue. I am not sure If i can trust the imputed variants.

**Comment by sinarueeger** [comment]
Hi Veera, let me discuss this with my colleagues and I will get back to you asap (some are still on vacation today).

**Comment by drveera** [comment]
Hi, thanks for the response. Now I figured the issue. There was a bug in the LDscore regression munge script that altered the Z scores in the output file. When I calculated GC lambda manually it was 1.02 which made sense. Now everything falls in to place. Thanks for this great software. 

Regards
Veera Manikandan Rajagopal MD
PhD Student
Department of Biomedicine
Aarhus University
Aarhus, Denmark

**Comment by sinarueeger** [comment]
Happy to hear that! 
Best,
Sina
