### ISSUE TITLE
branch <new-output-columns> : adding P.imp, N.imp and bst.imp + testing

### ISSUE THREAD

**Issue by sinarueeger** [sinarueeger/ssimp_software#20]
add to output: n.imp, p.value and st.effectsizes to output

**Comment by sinarueeger** [comment]
P_imp = normalCFD(z_imp)

**Comment by sinarueeger** [comment]
add to output: n.imp, p.value and st.effectsizes to output

**Comment by aaronmcdaid** [comment]
I've pushed code to print these to a branch called 'more.columns'. It's a really tiny change, so I'll simply copy in here directly.

Add this near the top of ssimp.cc:
```
#include<gsl/gsl_cdf.h>
```

... and add this to where the header is printed:
````
                        << '\t' << "P.imp"
                        << '\t' << "N.imp"
                        << '\t' << "bst.imp"
````

and this to the output:

```
                        << '\t' << 2.0*gsl_cdf_gaussian_P(-std::abs(z_imp), 1)      // P.imp
                        << '\t' << N_max * imp_qual                                 // N.imp
                        << '\t' << z_imp / std::sqrt(N_max*imp_qual)                // bst.imp

```

***Note***: sometimes the imp.qual is exactly zero (in my crazy tests anyway) which results in `N.imp=0` and `bst.imp=inf`. That's weird and I'm sure some users will be confused to see it

(I also intend to push a follow-up commit in the next hour which updates all the tests to include this extra column)

**Comment by sinarueeger** [comment]
Merged it and adapted docu/manual.md

**Comment by aaronmcdaid** [comment]
Please pull from 'more.columns' again. I finally pushed the test updates only a few minutes ago!

**Comment by sinarueeger** [comment]
Done
