### ISSUE TITLE
R function to calculate P value

### ISSUE THREAD

**Issue by drveera** [sinarueeger/ssimp_software#28]
Hi,

Could you tell how to calculate P values using R? For now I am doing like, `pnorm(abs(Z), lower.tail=FALSE)`  Is this right? I couldnt understand the formula you described in the manual. 

Regards,
Veera

**Comment by drveera** [comment]
I guess its `pnorm(abs(Z), lower.tail=FALSE)*2`.

**Comment by sinarueeger** [comment]
Correct! In case of super large z stats (as often in genomics) you might want to use the log option too. Otherwise you end up with p=0.

**Comment by drveera** [comment]
Sure. thanks. Also regarding the lambda I didnt specify anything. Whats the default value the script uses? does it calculated from sample size from reference panel?

**Comment by sinarueeger** [comment]
The default lambda (2/sqrt(n)) is fine. And yes, n is the number of individuals in the refpanel.

**Comment by sinarueeger** [comment]
The newest version (just uploaded) has the P value column included.

**Comment by drveera** [comment]
awesome. thanks :)
