### ISSUE TITLE
remove all the lambdas that are not controlled by the default

### ISSUE THREAD

**Issue by aaronmcdaid** [sinarueeger/ssimp_software#30]

**Comment by aaronmcdaid** [comment]
Done.

However, are you certain you want to do this? If I remember correctly, we deliberately decided to use a tiny lambda (1e-8) in some of the calculations, for example when computing the number of effective tests. The number of effective tests is used to compute the correct imputation quality.


Pushed to new branch 'remove.hardcoded.lambdas'

**Comment by sinarueeger** [comment]
We want it for the imputation quality. Not sure anymore about the number of effective tests. Will think about this again.

**Comment by sinarueeger** [comment]
#38
