### ISSUE TITLE
compile static version

### ISSUE THREAD

**Issue by sinarueeger** [sinarueeger/ssimp_software#33]
Tried to compile the static version of 0.2 on our server. 
`stu bin/ssimp-static`

Gave this error

```
Building @unconditional
Building bin/LIST_OF_HH_FILES
Building bin/ssimp-static
LINKER:/home/srueger/bin/g++  -O3  -Wall -Wextra -std=c++14  -lstdc++
LD_FLAGS:-lgsl -lgslcblas -lm  -lz
/usr/bin/ld: cannot find -lgsl
/usr/bin/ld: cannot find -lgslcblas
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
bin.stu:51:5: command for bin/ssimp-static failed with exit status 1
```

**Comment by aaronmcdaid** [comment]
I've sent an email to you, Patrick and Geert in the last few minutes. hpc1 already has the dynamic version of gsl installed `/usr/lib64/libgsl.so`, but we need the static version also `/usr/lib/libgsl.a` if we want to compile the static version of `ssimp`

In the meantime, I can compile it on my laptop. But that's not sustainable in the long run. Is there another linux machine you can access? I can't access either vital-it machine any more, but perhaps you can?

**Comment by sinarueeger** [comment]
I can access vitalit, but the problem is, that stu is not available there. 
I can use make. Which gives me these error messages:
stu/stu bin/ssimp
stu/stu: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by stu/stu)
stu/stu: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by stu/stu)
stu/stu: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by stu/stu)
stu/stu: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by stu/stu)
stu/stu: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by stu/stu)
make: *** [bin/ssimp] Error 1

**Comment by sinarueeger** [comment]
Lets use your linux version until geert has fixed the lib thing on hpc1. Ok for you? 
Last option is to compile it on the former group server, but I dont have high hopes for that one.

**Comment by aaronmcdaid** [comment]
I've compiled it and pushed it to a new branch called 'static-bin'

It's within a new folder called 'static-bin'. You might decide to rename that file (using `git mv`) before publishing it

I'm not sure how to fix that vital-it problem

**Comment by sinarueeger** [comment]
#35
