### ISSUE TITLE
(not urgent, but easy!) A gwas file was missing - I've added it back again

### ISSUE THREAD

**Issue by aaronmcdaid** [sinarueeger/ssimp_software#44]
Please merge the `readd.missing.gwas.file` branch.

It includes a file (`gwas/GIANT_HEIGHT_Wood_oneWindowOnChr22.tsv.gz`) that was removed earlier, but is still needed for one of the tests

**Comment by sinarueeger** [comment]
Sorry for deleting this one. I thought it needed "git rm" to remove a file. not only "rm"... 

I merged the branch.
